<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="QuestPDF" Version="2026.5.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\interTekLabERP.Business\interTekLabERP.Business.csproj" />
    <ProjectReference Include="..\interTekLabERP.Data\interTekLabERP.Data.csproj" />
    <ProjectReference Include="..\interTekLabERP.Entities\interTekLabERP.Entities.csproj" />
  </ItemGroup>

</Project>
